In [33]:
import pandas as pd
import numpy as np

In [34]:
# Q1
pd.__version__

'1.5.3'

In [35]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv"
df = pd.read_csv(url)

In [36]:
# Q2 and Q3
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [37]:
df.ocean_proximity.value_counts()

<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: ocean_proximity, dtype: int64

In [38]:
# Q4
df.ocean_proximity.nunique()

5

In [39]:
filter = df.ocean_proximity=='NEAR BAY'

In [40]:
# Q5
df[filter].median_house_value.mean()

259212.31179039303

In [41]:
ddf = df[filter]

In [42]:
ddf.isnull().sum()

longitude              0
latitude               0
housing_median_age     0
total_rooms            0
total_bedrooms        20
population             0
households             0
median_income          0
median_house_value     0
ocean_proximity        0
dtype: int64

In [43]:
ddf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2290 entries, 0 to 19104
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           2290 non-null   float64
 1   latitude            2290 non-null   float64
 2   housing_median_age  2290 non-null   float64
 3   total_rooms         2290 non-null   float64
 4   total_bedrooms      2270 non-null   float64
 5   population          2290 non-null   float64
 6   households          2290 non-null   float64
 7   median_income       2290 non-null   float64
 8   median_house_value  2290 non-null   float64
 9   ocean_proximity     2290 non-null   object 
dtypes: float64(9), object(1)
memory usage: 196.8+ KB


In [44]:
# AVG total_bedrooms
avg_bedrooms = df.total_bedrooms.mean()
avg_bedrooms

537.8705525375618

In [45]:
df.total_bedrooms.fillna(avg_bedrooms, inplace=True)

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20640 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [47]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [48]:
new_avg_bedrooms = df.total_bedrooms.mean()
new_avg_bedrooms

537.8705525375617

In [49]:
avg_bedrooms

537.8705525375618

In [59]:
# Q6 => mean didn't change (up to the 3rd number)

np.round(avg_bedrooms,3) == np.round(new_avg_bedrooms,3)

True

In [51]:
cols = ['housing_median_age','total_rooms','total_bedrooms']
data = df[df.ocean_proximity=='ISLAND'][cols]
data

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [52]:
X = data.to_numpy()
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [53]:
y = np.array([950,1300,800,1000,1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [54]:
XTX = X.T.dot(X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [55]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [56]:
w = XTX_inv.dot(X.T).dot(y)

In [57]:
w

array([23.12330961, -1.48124183,  5.69922946])

In [58]:
# Q7
w[-1]

5.6992294550655656